Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "Server-1",
          :box => "ubuntu/bionic64",
          :ip => "192.169.33.60",
          :ssh_port => '2200'
        },
        {
          :hostname => "Server-2",
          :box => "ubuntu/bionic64",
          :ip => "192.169.33.70",
          :ssh_port => '2201'
        },
      ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.provision :docker
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

            node.vm.provider :virtualbox do |vb|
                vb.memory = "1024"
            end
        end
    end
end
