version: "3.5"
services:
  jenkins_server:
    image: jenkinsci/blueocean
    container_name: jenkins_server
    restart: always
    ports:
     - "8080:8080"
     - "5000:5000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
    name: jenkins_data